# Generated by Django 4.1 on 2022-08-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_remove_script_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='type',
            field=models.CharField(default='usd', max_length=50),
        ),
    ]
