# Generated by Django 4.1 on 2022-08-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_script_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Script',
        ),
    ]
